// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	protocol "ashe/protocol"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// 注册用户
	Register(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error)
	Login(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error)
	Edit(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

var userRegisterStreamDesc = &grpc.StreamDesc{
	StreamName: "Register",
}

func (c *userClient) Register(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error) {
	out := new(protocol.Response)
	err := c.cc.Invoke(ctx, "/user/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var userLoginStreamDesc = &grpc.StreamDesc{
	StreamName: "Login",
}

func (c *userClient) Login(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error) {
	out := new(protocol.Response)
	err := c.cc.Invoke(ctx, "/user/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var userEditStreamDesc = &grpc.StreamDesc{
	StreamName: "Edit",
}

func (c *userClient) Edit(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error) {
	out := new(protocol.Response)
	err := c.cc.Invoke(ctx, "/user/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserService is the service API for User service.
// Fields should be assigned to their respective handler implementations only before
// RegisterUserService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type UserService struct {
	// 注册用户
	Register func(context.Context, *protocol.Request) (*protocol.Response, error)
	Login    func(context.Context, *protocol.Request) (*protocol.Response, error)
	Edit     func(context.Context, *protocol.Request) (*protocol.Response, error)
}

func (s *UserService) register(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/user/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Register(ctx, req.(*protocol.Request))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *UserService) login(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/user/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Login(ctx, req.(*protocol.Request))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *UserService) edit(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/user/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Edit(ctx, req.(*protocol.Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterUserService registers a service implementation with a gRPC server.
func RegisterUserService(s grpc.ServiceRegistrar, srv *UserService) {
	srvCopy := *srv
	if srvCopy.Register == nil {
		srvCopy.Register = func(context.Context, *protocol.Request) (*protocol.Response, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
		}
	}
	if srvCopy.Login == nil {
		srvCopy.Login = func(context.Context, *protocol.Request) (*protocol.Response, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
		}
	}
	if srvCopy.Edit == nil {
		srvCopy.Edit = func(context.Context, *protocol.Request) (*protocol.Response, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "user",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Register",
				Handler:    srvCopy.register,
			},
			{
				MethodName: "Login",
				Handler:    srvCopy.login,
			},
			{
				MethodName: "Edit",
				Handler:    srvCopy.edit,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "user.proto",
	}

	s.RegisterService(&sd, nil)
}
