// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cronjob.proto

package cronjob

import (
	protocol "ashe/protocol"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("cronjob.proto", fileDescriptor_9693a1980b1a682f) }

var fileDescriptor_9693a1980b1a682f = []byte{
	// 96 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2e, 0xca, 0xcf,
	0xcb, 0xca, 0x4f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x49, 0x2c, 0xce, 0x48, 0xd5,
	0x07, 0xb3, 0x93, 0xf3, 0x73, 0xe0, 0x0c, 0x88, 0xac, 0x91, 0x25, 0x17, 0x3b, 0x54, 0xb9, 0x90,
	0x1e, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x90, 0xa0, 0x1e, 0x5c, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x94, 0x10, 0xb2, 0x50, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x12, 0x43, 0x12, 0x1b,
	0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x20, 0xfb, 0x55, 0xa5, 0x70, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CronjobClient is the client API for Cronjob service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CronjobClient interface {
	Add(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error)
}

type cronjobClient struct {
	cc *grpc.ClientConn
}

func NewCronjobClient(cc *grpc.ClientConn) CronjobClient {
	return &cronjobClient{cc}
}

func (c *cronjobClient) Add(ctx context.Context, in *protocol.Request, opts ...grpc.CallOption) (*protocol.Response, error) {
	out := new(protocol.Response)
	err := c.cc.Invoke(ctx, "/cronjob/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CronjobServer is the server API for Cronjob service.
type CronjobServer interface {
	Add(context.Context, *protocol.Request) (*protocol.Response, error)
}

// UnimplementedCronjobServer can be embedded to have forward compatible implementations.
type UnimplementedCronjobServer struct {
}

func (*UnimplementedCronjobServer) Add(ctx context.Context, req *protocol.Request) (*protocol.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterCronjobServer(s *grpc.Server, srv CronjobServer) {
	s.RegisterService(&_Cronjob_serviceDesc, srv)
}

func _Cronjob_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CronjobServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cronjob/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CronjobServer).Add(ctx, req.(*protocol.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cronjob_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cronjob",
	HandlerType: (*CronjobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Cronjob_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cronjob.proto",
}
